services:
  - type: web
    name: ai-chatbot
    env: node
    plan: free
    runtime: node20
    buildCommand: |
      npm install --prefix client --include=dev
      npm run build --prefix client
      npm install --prefix server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
